test_shutdown_failure: error: This error was triggered on purpose.
